---
- name: Configure Cron Job
  hosts: dbserver
  vars:
    ansible_user: ec2-user
    ansible_password: '{{ lookup("env", "ANSIBLE_PASSWORD") }}'
  become: yes
  become_user: ec2-user
  tasks:
    - name: Add Cron Job
      cron:
        name: "My Cron Job"
        minute: "*/1"
        job: " sh /home/ec2-user/Ansible-RealTime-Projects/backup-s3.sh"
