---
 - name: this is my first playbook
   hosts: dbserver
   become: yes
   become_user: ec2-user
   tasks:
     - name: Take Mysql backup
       shell: mysqldump -u root --password="{{ db_pass }}"  kritika  tblEmployee1 > /tmp/dump3.sql
     - name: Push Mysql backup to s3 bucket
       shell: aws s3 cp  /tmp/dump3.sql s3://mysql-backup-s3-new
