---
- name: Configure Cron Job
  hosts: dbserver
  vars:
    ansible_user: ec2-user
    ansible_password: '{{ lookup("env", "ANSIBLE_PASSWORD") }}'
  become: yes
  become_user: ec2-user
  vars_files:
    - db_pass.yml
  tasks:
    - name: Copy file with owner and permissions
      copy:
        src: /home/ec2-user/Ansible-RealTime-Projects/backup-s3.sh
        dest: /home/ec2-user/backup-s3.sh
        mode: '0755'
    - cron:
        name: db_pass
        env: yes
        value: {{ db_pass }}
    - name: Add Cron Job
      cron:
        name: "My Cron Job"
        minute: "*/1"
        job: "sh /home/ec2-user/backup-s3.sh"
